version: "3.1"

services:
  mongo:
    container_name: mongo-chat
    image: mongo
    restart: always
    ports:
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
